name: Bundle js

on:
  workflow_dispatch:
  push:
    branches: ["master", "development"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: development
          path: development

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build development
        run: |
          cd development
          npm install
          npm run build

      - name: Build master
        run: |
          npm install
          npm run build

      - name: Move development
        run: |
          mv development/dist dist/beta

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
